### PR TITLE
Enabling coupling_map as options to the AI Synthesis passes

### PR DESCRIPTION
**Pull request by d-kremer**
### Summary

Currently, AI Synthesis passes only allow users to specify a `backend_name`. This allows users to specify custom `coupling_map` for the AI Synthesis passes.

### CODE REVIEW

**Review by cbjuan — DISMISSED** [review]
Code LGTM 

Let's wait for @y4izus or @jesus-talavera-ibm review to check if the PR fulfills everything needed in the repo for new releases

**Review by y4izus — CHANGES_REQUESTED** [review]
Since this PR includes a new functionality, we need to add the release notes and increase the minor version. There is a new [minor version ongoing](https://github.com/Qiskit/qiskit-ibm-transpiler/pull/69/files), so a conversation is happening to know the minor version we should assign to this PR

**Review by jesus-talavera-ibm — DISMISSED** [review]
Added release notes. LGTM!

**Review by jesus-talavera-ibm — DISMISSED** [review]
Added tests

**Review by y4izus — APPROVED** [review]

**Review by jesus-talavera-ibm — APPROVED** [review]

**Review by jesus-talavera-ibm — APPROVED** [review]

**Review by cbjuan — APPROVED** [review]

**Pull request merged**
