### PR TITLE
Add a linter to check the images' alt text

### PR DESCRIPTION
**Pull request by arnaucasau**
In order to meet the [IBM Accessibility Requirements](https://www.ibm.com/able/requirements/requirements) for the API docs, we need to ensure that all images have appropriate alt text so that users can understand any meaningful visuals. The alt text should serve the same purpose as the images on the page, conveying the same meaning rather than describing visual characteristics. In addition, if an image contains important words for understanding the content, the alt text should include those words as well.

This PR adds a linter to check that all images have alt text. The current invalid images, if any, have been included in an allowlist that will help us to not break CI before the text is added.

If the script detects an image without alt text, it will show an error indicating the file where the image is located and the line where we are using a sphinx directive like `.. image::` or `.. plot::` that generates an image. Example:

```
💔 Some images are missing the alt text

Errors found in qiskit_ibm_runtime/fake_provider/__init__.py:
- Error in line 34: .. plot::

Alt text is crucial for making documentation accessible to all users. It should serve the same purpose as the images on the page, conveying the same meaning rather than describing visual characteristics. When an image contains words that are important to understanding the content, the alt text should include those words as well.
```

To fix the error, the `:alt: [Your text here]` option must be added under the lines indicated in the error messages. However, If the `.. plot::` directive is used, but no image is generated, you can use the option `:nofigs:`.

### CODE REVIEW

**Review by Eric-Arellano — APPROVED** [review]

**Review by cbjuan — APPROVED** [review]
Thanks

**Comment by Eric-Arellano** [comment]
@cbjuan I think this fails CI because the PR is from a fork? I'm not sure if you want to merge on red.

**Review by jesus-talavera-ibm — APPROVED** [review]

**Comment by jesus-talavera-ibm** [comment]
> @cbjuan I think this fails CI because the PR is from a fork? I'm not sure if you want to merge on red.

@y4izus was working on fixing test in this PR: https://github.com/Qiskit/qiskit-ibm-transpiler/pull/128 We can wait until this one is merged

**Comment by arnaucasau** [comment]
Superseded by https://github.com/Qiskit/qiskit-ibm-transpiler/pull/138

**Pull request closed without merging**
